"use client";
import React from 'react';
import { VerticalTimeline, VerticalTimelineElement } from 'react-vertical-timeline-component';
import 'react-vertical-timeline-component/style.min.css';

const Data = [
  {
    id: 1,
    title: "step1",
    description: "Industry leading Optical Character Recognition (OCR) technology is used to reliably convert the handwritten text to text for computational purposes.",
  },
  {
    id: 2,
    title: "step2",
    description: "Sophisticated AI interprets the answers and maps it to the corresponding question for further evaluation.",
  },
  {
    id: 3,
    title: "step3",
    description: "Our cutting AI model evaluates the student's answer with respect to the given answer key and matches any provided keywords.",
  },
  {
    id: 4,
    title: "step4",
    description: "Post evaluation the AI model gives an appropriate score to each answer and totals up all the marks at the end to get total marks.",
  },
  {
    id: 5,
    title: "step5",
    description: "For institutions, data driven insights are generated by finding the raw statistical data while at the same time identifying patterns in answer scripts to make teaching more tailored for the students.",
  },
  
];

const HowItWorks = () => {
  

  return (
    <section id="experience" className='flex justify-center items-center flex-col py-20 text-white'>
      <h2 className='text-black sm:mb-[3.4rem] sm:text-5xl lg:text-6xl font-bold mt-10 font-sans xsm:text-4xl'>How It works <span className='text-blue-600'>?</span></h2>
            <VerticalTimeline lineColor="#1E88E5" animate={true}>
              {Data.map((project) => (
          (<React.Fragment key={project.id}>
              <VerticalTimelineElement visible contentStyle={{background:"#E5F4FF",padding:"1.3rem 2rem"}}
              contentArrowStyle={{borderRight:'1rem solid black'}}
              iconStyle={{ visibility:'hidden'}}
              date={project.title}>
              <p className="text-black">{project.description}</p>
              </VerticalTimelineElement>
             </React.Fragment>
          )
        ))}
        </VerticalTimeline>
    </section>
  )
}

export default HowItWorks;
